language: java

before_install:
    - |
      echo "Cloning commons"
      git clone --branch=master https://github.com/eskaton/commons.git eskaton/commons
      cd eskaton/commons
      mvn -B install
      cd -
