language: java
sudo: false

jdk: oraclejdk11

addons:
   sonarcloud:
      organization: eskaton-github

before_install:
   - |
     git clone --branch=master https://github.com/eskaton/commons.git eskaton/commons
     cd eskaton/commons
     mvn -B clean install
     cd -

install: true

script:
   - mvn -e -B clean org.jacoco:jacoco-maven-plugin:prepare-agent install jacoco:report sonar:sonar -Dsonar.login=$SONAR_TOKEN -Dsonar.projectKey=eskaton_asn4j

cache:
   directories:
      - '$HOME/.m2/repository'
      - '$HOME/.sonar/cache'
