language: java

addons:
  sonarcloud:
    organization: "eskaton-github"
    token:
      secure: $SONAR_TOKEN

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
  directories:
	- '$HOME/.sonar/cache'

before_install:
    - |
      echo "Cloning commons"
      git clone --branch=master https://github.com/eskaton/commons.git eskaton/commons
      cd eskaton/commons
      mvn -B install
