X681 DEFINITIONS ::=
BEGIN

TEST ::= CLASS {
    &bitStringField  BIT STRING,
    &booleanField    BOOLEAN,
    &enumField       ENUMERATED {a, b, c},
    &intField        INTEGER {a(1), b(3), c(5)}
}

TestSet TEST ::= {
    { &bitStringField '0101'B,
      &booleanField    TRUE,
      &enumField       a,
      &intField        c
    }
}

TestSequence1 ::= SEQUENCE {
   bitStringField TEST.&bitStringField
}

TestSequence2 ::= SEQUENCE {
   booleanField TEST.&booleanField
}

TestSequence3 ::= SEQUENCE {
   enumField TEST.&enumField
}

TestSequence4 ::= SEQUENCE {
   intField TEST.&intField
}

END
