X681 DEFINITIONS ::=
BEGIN

TEST ::= CLASS {
    &bitStringField        BIT STRING,
    &booleanField          BOOLEAN,
    &enumField             ENUMERATED {a, b, c},
    &intField              INTEGER {a(1), b(3), c(5)},
    &nullField             NULL,
    &octetStringField      OCTET STRING,
    &visibleStringField    VisibleString,
    &generalStringField    GeneralString,
    &graphicStringField    GraphicString,
    &ia5StringField        IA5String,
    &videotexStringField   VideotexString,
    &teletexStringField    TeletexString,
    &printableStringField  PrintableString,
    &numericStringField    NumericString,
    &utf8StringField       UTF8String,
    &universalStringField  UniversalString,
    &bmpStringField        BMPString,
    &sequenceOfField       SEQUENCE OF INTEGER,
    &setOfField            SET OF INTEGER,
    &sequenceField         SEQUENCE { a INTEGER, b BOOLEAN },
    &setField              SET { a INTEGER, b BOOLEAN },
    &choiceField           CHOICE { a INTEGER, b BOOLEAN }
}

TestSet TEST ::= {
    { &bitStringField        '0101'B,
      &booleanField          TRUE,
      &enumField             a,
      &intField              c,
      &nullField             NULL,
      &octetStringField      '0BD9'H,
      &visibleStringField    "abc",
      &generalStringField    "abc",
      &graphicStringField    "abc",
      &ia5StringField        "abc",
      &videotexStringField   "abc",
      &teletexStringField    "abc",
      &printableStringField  "abc",
      &numericStringField    "123",
      &utf8StringField       "äöü",
      &universalStringField  "äöü",
      &bmpStringField        "äöü",
      &sequenceOfField       {1, 2, 3},
      &setOfField            {1, 2, 3},
      &sequenceField         {a 1, b TRUE},
      &setField              {a 1, b TRUE},
      &choiceField           b: TRUE
    }
}

TestSequence1 ::= SEQUENCE {
   bitStringField TEST.&bitStringField
}

TestSequence2 ::= SEQUENCE {
   booleanField TEST.&booleanField
}

TestSequence3 ::= SEQUENCE {
   enumField TEST.&enumField
}

TestSequence4 ::= SEQUENCE {
   intField TEST.&intField
}

TestSequence5 ::= SEQUENCE {
   nullField TEST.&nullField
}

TestSequence6 ::= SEQUENCE {
   octetStringField TEST.&octetStringField
}

TestSequence7 ::= SEQUENCE {
   visibleStringField TEST.&visibleStringField
}

TestSequence8 ::= SEQUENCE {
   generalStringField TEST.&generalStringField
}

TestSequence9 ::= SEQUENCE {
   graphicStringField TEST.&graphicStringField
}

TestSequence10 ::= SEQUENCE {
   ia5StringField TEST.&ia5StringField
}

TestSequence11 ::= SEQUENCE {
   videotexStringField TEST.&videotexStringField
}

TestSequence12 ::= SEQUENCE {
   teletexStringField TEST.&teletexStringField
}

TestSequence13 ::= SEQUENCE {
   printableStringField TEST.&printableStringField
}

TestSequence14 ::= SEQUENCE {
   numericStringField TEST.&numericStringField
}

TestSequence15 ::= SEQUENCE {
   utf8StringField TEST.&utf8StringField
}

TestSequence16 ::= SEQUENCE {
   universalStringField TEST.&universalStringField
}

TestSequence17 ::= SEQUENCE {
   bmpStringField TEST.&bmpStringField
}

TestSequence18 ::= SEQUENCE {
   sequenceOfField TEST.&sequenceOfField
}

TestSequence19 ::= SEQUENCE {
   setOfField TEST.&setOfField
}

TestSequence20 ::= SEQUENCE {
   sequenceField TEST.&sequenceField
}

TestSequence21 ::= SEQUENCE {
   setField TEST.&setField
}

TestSequence22 ::= SEQUENCE {
   choiceField TEST.&choiceField
}

END
