X680-51-8 DEFINITIONS ::=
BEGIN

TestSetOf1 ::= SET SIZE (1) OF INTEGER (0..4)
TestSetOf2 ::= TestSetOf1 (WITH COMPONENT (1..2))
TestSetOf3 ::= SET SIZE (1) OF SET OF INTEGER (0..4)
TestSetOf4 ::= TestSetOf3 (WITH COMPONENT (SIZE (2)))
TestSetOf5 ::= TestSetOf3 (WITH COMPONENT (WITH COMPONENT (1..2)))
TestSetOf6 ::= TestSetOf3 (WITH COMPONENT (SIZE (2) | (WITH COMPONENT (1..2))))
TestSetOf7 ::= TestSetOf3 (WITH COMPONENT (SIZE (2) ^ (WITH COMPONENT (1..2))))
TestSetOf8 ::= TestSetOf3 (WITH COMPONENT (SIZE (2) EXCEPT (WITH COMPONENT (1..2))))

TestSequenceOf1 ::= SEQUENCE SIZE (1) OF INTEGER (0..4)
TestSequenceOf2 ::= TestSequenceOf1 (WITH COMPONENT (1..2))

TestSequence1 ::= SEQUENCE {
    a INTEGER,
    b BOOLEAN,
    ...
}
TestSequence2 ::= TestSequence1 (WITH COMPONENTS {a (1..2), b (TRUE)})
TestSequence3 ::= SEQUENCE {
    c TestSequence2,
    ...,
    d BOOLEAN
} (WITH COMPONENTS {c (WITH COMPONENTS {a (1), b (TRUE)}), d (FALSE)})
TestSequence4 ::= SEQUENCE {
    c SEQUENCE {
        a INTEGER,
        b BOOLEAN,
        ...
    },
    ...,
    d BOOLEAN
} (WITH COMPONENTS {c (WITH COMPONENTS {a (1), b (TRUE)}), d (FALSE)})


-- Test all types
TestSetOf9 ::= SET OF BOOLEAN
TestSetOf10 ::= TestSetOf9 (WITH COMPONENT (TRUE))
TestEnumerated1 ::= ENUMERATED {a, b, c}
TestSetOf11 ::= SET OF TestEnumerated1
TestSetOf12 ::= TestSetOf11 (WITH COMPONENT (a))
TestSetOf13 ::= SET OF NULL
TestSetOf14 ::= TestSetOf13 (WITH COMPONENT (NULL))
TestSetOf15 ::= SET OF OBJECT IDENTIFIER
TestSetOf16 ::= TestSetOf15 (WITH COMPONENT ({ 0 3 6 3 }))
TestSetOf17 ::= SET OF RELATIVE-OID
TestSetOf18 ::= TestSetOf17 (WITH COMPONENT ({ 3 6 3 }))
TestSetOf19 ::= SET OF OID-IRI
TestSetOf20 ::= TestSetOf19 (WITH COMPONENT ("/ISO/a/b/e"))
TestSetOf21 ::= SET OF RELATIVE-OID-IRI
TestSetOf22 ::= TestSetOf21 (WITH COMPONENT ("a/b/e"))
TestSetOf23 ::= SET OF OCTET STRING
TestSetOf24 ::= TestSetOf23 (WITH COMPONENT ('0101'B))
TestSetOf25 ::= SET OF TestSequenceOf2
TestSetOf26 ::= TestSetOf25 (WITH COMPONENT (WITH COMPONENT (1)))

TestSequence5 ::= SEQUENCE {
    a ENUMERATED {a, b, c}
} (WITH COMPONENTS {a (a|b)})

END
