X680-51-8 DEFINITIONS ::=
BEGIN

TestSetOf1 ::= SET SIZE (1) OF INTEGER (0..4)
TestSetOf2 ::= TestSetOf1 (WITH COMPONENT (1..2))
TestSetOf3 ::= SET SIZE (1) OF SET OF INTEGER (0..4)
TestSetOf4 ::= TestSetOf3 (WITH COMPONENT (SIZE (2)))
TestSetOf5 ::= TestSetOf3 (WITH COMPONENT (WITH COMPONENT (1..2)))
TestSetOf6 ::= TestSetOf3 (WITH COMPONENT (SIZE (2) | (WITH COMPONENT (1..2))))
TestSetOf7 ::= TestSetOf3 (WITH COMPONENT (SIZE (2) ^ (WITH COMPONENT (1..2))))
TestSetOf8 ::= TestSetOf3 (WITH COMPONENT (SIZE (2) EXCEPT (WITH COMPONENT (1..2))))

END
