X680-20 DEFINITIONS ::=
BEGIN

TestEnumeration ::= ENUMERATED {
	m(testInt), a, b, c(0), ..., d, e(5), f, g(9), h
}

testInt INTEGER ::= -3

testEnumerationValue1 TestEnumeration ::= e

testEnumerationValue2 TestEnumeration ::= testEnumerationValue1

TestEnumerations ::= SEQUENCE {
    testEnumeration1 TestEnumeration DEFAULT m,
    testEnumeration2 TestEnumeration DEFAULT testEnumerationValue1,
    testEnumeration3 TestEnumeration DEFAULT testEnumerationValue2
}

END
