X680-51-2 DEFINITIONS ::=
BEGIN

bitStringValue BIT STRING ::= '100'B

TestBitString1 ::= BIT STRING (ALL EXCEPT bitStringValue)
TestBitString2 ::= BIT STRING (('000'B | '001'B | '010'B | '011'B | bitStringValue | '101'B | '110'B | '111'B) EXCEPT '010'B)
TestBitString3 ::= BIT STRING ((('000'B | '001'B | '010'B | '011'B) ^ ('001'B | '010'B | '011'B)) EXCEPT '010'B)
TestBitString4 ::= BIT STRING (('000'B | '001'B | '010'B) ^ ('001'B | '010'B), ...)
-- TestBitString5 must be extensible
TestBitString5 ::= TestBitString4
-- TestBitString6 must not be extensible
TestBitString6 ::= TestBitString4 (ALL EXCEPT '001'B)

TestBoolean1 ::= BOOLEAN (ALL EXCEPT TRUE)
TestBoolean2 ::= BOOLEAN (TRUE)
TestBoolean3 ::= BOOLEAN (FALSE)
TestBoolean4 ::= BOOLEAN (TRUE | FALSE)
TestBoolean5 ::= BOOLEAN ((TRUE | FALSE) ^ TRUE)
TestBoolean6 ::= TestBoolean4 (ALL EXCEPT FALSE)

TestEnumeration1 ::= ENUMERATED {
        a, b, c, d
}

TestEnumeration2 ::= TestEnumeration1 (a | b)
TestEnumeration3 ::= TestEnumeration1 ((a | b | c) ^ (b | c | d))
TestEnumeration4 ::= TestEnumeration1 (ALL EXCEPT d)

TestInteger1 ::= INTEGER (1 | 2)
TestInteger2 ::= INTEGER (ALL EXCEPT 0)
TestInteger3 ::= INTEGER (((1 | 2 | 3) ^ (2 | 3)) EXCEPT 3)

TestNull1 ::= NULL (NULL)
TestNull2 ::= NULL (ALL EXCEPT NULL)
TestNull3 ::= NULL ((NULL ^ NULL) EXCEPT NULL)

END
