X680-13 DEFINITIONS ::=
BEGIN

IMPORTS
    TestEnumeratedType1, testInteger1
        FROM X680-13-Sub1;

TestEnumeratedType2 ::= TestEnumeratedType1

TestSequence1 ::= SEQUENCE {
   a INTEGER DEFAULT testInteger1,
   b INTEGER DEFAULT X680-13-Sub1.testInteger2
}

END
