X680-25 DEFINITIONS ::=
BEGIN

TestSequence0 ::= SEQUENCE {
	a BOOLEAN
}

TestSequence1 ::= SEQUENCE {
	a INTEGER,
	b BOOLEAN,
	c OCTET STRING 
}

TestSequence2 ::= SEQUENCE {
	a INTEGER,
	b BOOLEAN OPTIONAL,
	c OCTET STRING 
}

TestBitString1 ::= BIT STRING {
  test-a(0),
  test-b(one),
  test-c(two)
}

TestBitString2 ::= TestBitString1

TestNamedInteger2 ::= INTEGER {
	two(2)
}

one INTEGER ::= 1

two TestNamedInteger2 ::= two

testBitString2 TestBitString2 ::= { test-a, test-b }

TestSequence3 ::= SEQUENCE {
	a INTEGER,
	b BOOLEAN,
	c OCTET STRING DEFAULT "test",
	d BIT STRING DEFAULT '000100100011010001010110011110011010101111001101111011110000'B,
	e BIT STRING DEFAULT '0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF'H,
	f BIT STRING DEFAULT testBitString2,
	g TestBitString2 DEFAULT { test-a, test-c },
	h TestBitString2 DEFAULT { }
}

intValue INTEGER ::= 4711

TestSequence4 ::= SEQUENCE {
	a INTEGER DEFAULT intValue,
	b BOOLEAN,
	c OCTET STRING
}

TestSequence5 ::= SEQUENCE {
	a INTEGER DEFAULT 23,
	...,
	z INTEGER
}

TestSequence6 ::= SEQUENCE {
	COMPONENTS OF TestSequence5,
	b BOOLEAN
}

TestSequence7 ::= SEQUENCE {
	a INTEGER,
	...,
	b INTEGER
}

END
